### ISSUE TITLE
"Copying content"

### ISSUE THREAD

**Issue by jernst** [swicg/activitypub-data-portability#28]
I'm not sure I like this phrase. "Copy" sounds like an exact duplicate, and chances are it won't be:

* the source and destination servers may run different software with different schemas
* the source and destination servers may run the same software but at different versions (and thus perhaps different schemas)
* the source and destination servers have different DNS names and user handles, and some of the content will need to be adjusted
* the destination server already may have some content, and what is imported needs to be reconciled with what's there already.

Maybe "fetching content" instead of "copying content" would be better? Certainly other possibilities ...

**Comment by lisad** [comment]
I can change the phase name and section header to Fetching Content because it's a good phrase, although I like the word "copying" to convey that there will be two copies of the data for at least a while.  Would "Fetching and Saving" be a good phrase? Actually, now that I look at it that way, it might be really good to break that large section up into "Fetching data" and "Saving objects".

**Comment by jernst** [comment]
Two sections sounds like a good idea to me because they describe distinct challenges. "Saving" then also might describe a lot more than Apple-S :-)
